### ISSUE TITLE
Feature Request: Block Parser to parse existing Block JSON into an Object Tree

### ISSUE THREAD

**Issue by Andi1986** [jeremeamia/slack-block-kit#13]
Right now we can build the Block Json from the Element Objects, but what if we have the json and want to modify/add/delete something ?
The best scenario for this, and the reason why i request this feature, is actually the External Data Source for the Select Menu. on interacting with the dropdown, slack will send a request to the App's configured Options Load Api :
https://api.slack.com/reference/block-kit/block-elements#external_select
apparently slack did **not** docuement the request body of this particular request they send but i have debugged it and it seems inside the view property they simply send back the same **whole** block json that was actually previously sent to slack to open the view.
in addition to that they send further information like what value was typed into the input field and stuff like that (not in the block part!)

So we need some kind of Parser which accepts this Block JSON and creates an Object Tree so we can then modify it and then encode to json like in status quo.

**Comment by Andi1986** [comment]
i can actually try on this

**Comment by jeremeamia** [comment]
My email address is on my GitHub profile. I would be interested in your idea for you would do it.

**Comment by Andi1986** [comment]
Im working on it, i'd say 40% done

**Comment by jeremeamia** [comment]
I will work on this eventually. As I've gotten deeper into building apps, I've realized that this is pretty important for working with Modals.

**Comment by jeremeamia** [comment]
I'm working on this in #16. It's a fairly significant effort it seems, but it should be useful.

**Comment by jeremeamia** [comment]
@Andi1986 if you want, you can give the [`hydration` branch](https://github.com/jeremeamia/slack-block-kit/tree/hydration) a try.

**Comment by Andi1986** [comment]
Cool, thank you! Didnt have time to work on it myself unfortionatly but I think this feature will bring your project to the next level.
I've had a rough look on the code, it looks good and alot of code 😄. I was always thinking if there was a more dynamic way for hydrating instead of implementing the same method in each element but probably its just not possible because of too many edge cases.
