### ISSUE TITLE
Need to add max limit on modal title

### ISSUE THREAD

**Issue by nurul-umbhiya** [jeremeamia/slack-block-kit#3]
Hi,
I'm getting error if modal title is more than 24 character long.  I think we need to add some validation for modal title.

Errors I'm getting from slack api:
[0] => [ERROR] failed to match all allowed schemas [json-pointer:/view/title]
[1] => [ERROR] must be less than 24 characters [json-pointer:/view/title/text]

eg code: 
$msg = SlackBuilder::newModal();
$msg->title('this is a really long title')

**Comment by jeremeamia** [comment]
Sounds good. Fixed in 9ca32b3dbece22848c31f75506725edf32bedd80

**Comment by nurul-umbhiya** [comment]
Thankyou. Let me know if I can help implementing other pending task for this project.
