### ISSUE TITLE
Button block does not require value

### ISSUE THREAD

**Issue by shaneiseminger** [jeremeamia/slack-block-kit#6]
`Inputs\Button` throws an exception when no `value` is set. However, I noticed that the [Slack Block Kit](https://api.slack.com/reference/block-kit/block-elements) docs say the value isn't required.

Am I missing something? Will submit a PR if not.

**Comment by jeremeamia** [comment]
Looks like you're right. Go ahead with the PR. Thanks.

**Comment by jeremeamia** [comment]
Fixed by #7
