### ISSUE TITLE
Send blocks as attachments

### ISSUE THREAD

**Issue by aronpc** [jeremeamia/slack-block-kit#8]
Can I send messages as attachments?
https://api.slack.com/reference/messaging/attachments#example
Thank you for this amazing package .

**Comment by jeremeamia** [comment]
Attachments are the legacy way to format messages. I built this library to model only the new block kit style of messages.

...But it looks like you can now send blocks in an attachments message now, which is a new feature. This library does not support that yet.

I haven't experimented with this much, but according to the docs and the Block Kit Builder, it looks like we could add a new `Surface` called `Attachments`, and do something like this:
```php
<?php

declare(strict_types=1);

namespace Jeremeamia\Slack\BlockKit\Surfaces;

class Attachments extends Surface
{
    /** @var string */
    private $color;

    public function color(string $color): self
    {
        $this->color = $color;

        return $this;
    }

    public function toArray(): array
    {
        $data = [];

        if (!empty($this->color)) {
            $data['color'] = $this->color;
        }
        
        $data += parent::toArray();

        return ['attachments' => $data];
    }
}
```
I'd be open to a pull request like this with tests.

In the meantime, you could compose a `Message` with blocks, and then do:
```php
$attachments = json_encode(['attachments' => ['color' => '#ff000'] + $message->toArray()]);
```

**Comment by mic-oliveira** [comment]
Can I create a trait and do something like copy a block to an attachment? So I believe that I would not need to create a new class for the message, because when I looked at the code I saw that an Attachment class would depend on an inheritance with the Element or an interface in common with the surface to maintain the behavior of the class identical to the Surface class.
And congratulations on the great package!

**Comment by jeremeamia** [comment]
Thanks, and good question. Can you provide an example of what you mean? I'm not sure I understand what you are trying to do.

**Comment by mic-oliveira** [comment]
I thought of something similar to this in a simple approach... 

```
<?php


namespace Jeremeamia\Slack\BlockKit\Surfaces;


trait AttachmentTrait
{
    private $color;

    private $attachments;

    public function asAttach()
    {
        $this->attachments=['attachments' => ['color' => $this->color??'#ff000'] + parent::toArray()];
        return $this->attachments;
    }

    public function color(string $color): self
    {
        $this->color = $color;

        return $this;
    }
}
```

```
<?php

declare(strict_types=1);

namespace Jeremeamia\Slack\BlockKit\Surfaces;

class Message extends Surface
{
    use AttachmentTrait;

    public const EPHEMERAL = 'ephemeral';
    public const IN_CHANNEL = 'in_channel';

    /** @var string */
    private $responseType = self::EPHEMERAL;

    /**
     * Configures whether the message is sent to the entire channel or not.
     *
     * @param bool $inChannel
     * @return Message
     */
    public function inChannel(bool $inChannel): self
    {
        $this->responseType = $inChannel ? self::IN_CHANNEL : self::EPHEMERAL;

        return $this;
    }

    public function toArray(): array
    {
        return ['response_type' => $this->responseType] + parent::toArray();
    }
}

```

**Comment by mic-oliveira** [comment]
The other approach would be something like this ... creating a common interface between Surface and Attach to ensure that any of the classes called would maintain the same behavior, I did not get to test this in the code. But would it be possible correct? One question is which of the two approaches would fit best or whether they would be the best ways ...

```
class TestAttachment
{
    private TesteInterface $teste;

    /**
     * TestAttachment constructor.
     * @param TesteInterface $teste
     */
    public function __construct(TesteInterface $teste)
    {
        $this->teste = $teste;
    }

    public function handle()
    {
        $this->teste->handle(new Button());
    }
}
```
```
interface TesteInterface
{
    public function handle(Element $element);
}
```

**Comment by mic-oliveira** [comment]
And thanks again! Your package saved the day! =)

**Comment by jeremeamia** [comment]
YW... and sorry, I forgot all about this. I'll think about how I could make this work, but this gives me an idea of what you are needing. Thanks.

**Comment by jeremeamia** [comment]
@aronpc @mic-oliveira Final circled back to this with #14 as the result. Thanks for calling it to my attention.
